<?php 
        $strEnvConfigFile = '../environment/config.php';
    $intLevel = 0;
    while (!file_exists($strEnvConfigFile)) {
       $strEnvConfigFile = '../' . $strEnvConfigFile;
       $intLevel++;
       // Iterate up 4 levels before giving up - this should never happen!
       if ($intLevel > 7) {
           die('Fatal error - environment configuration file could not be located');
       }
    }
    include_once $strEnvConfigFile;

	$strPageTitle = 'South Africa Power Generation Projects Nuclear';
	$strPageDescription = 'Africa Power Generation Projects Overview Nuclear Plants';
	$strPageKeywords = 'Africa Power Generation Projects, Africa Power Generation Recruitment';
	$strPageAuthor = 'AdoGreen Africa Recruiment Agency';
	$strPageImg = ENV_ROOTURL . '/assets/img/blog/nuclear-khoeberg.jpg';
	$strPageCountry = 'Africa';
	$strPageSector = 'energy-power-generation';
	$strPageJobList = '';

    include_once ENV_ROOT . 'includes/header.php';
?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $strPageTitle; ?></h1>
            <p class="post-meta">
                Published: Aug 2017
            </p>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <img class="img-responsive" src="<?php echo $strPageImg; ?>" width="100%" alt "<?php echo $strPageTitle; ?>">
        <div class="container-fluid breadcrumb">
    <div class="row">
        <div class="container">
            <div class="col-md-12">
                <ol class="breadcrumb">
                          <li><a href="/index.php">AdoGreen Recruitment Africa</a></li>
                          <li class="active">South Africa Power Generation Projects Nuclear</li>
                    </ol>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row margin-20">
        <div class="col-md-12">
            <header class="post-header">
            <h1 class="post-title">South Africa Power Generation Projects Nuclear</h1>
            <p class="post-meta">Jun 1, 2016</p>
            </header>
            <hr>
        </div>

    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="col-md-5">
                <img class="img-responsive" src="/assets/img/blog/nuclear-khoeberg.jpg" width="100%" alt="Africa Power Generation Projects, Africa Power Generation Recruitment">
            </div>
            <article class="post-content">
                <h3 id="france-confident-sa-nuke-power-build-will-push-ahead">France confident SA nuke power build will push ahead</h3>

<p>Johannesburg – France remains confident the South African government will go ahead with its project to build 9 600 megawatts of extra nuclear power generation – despite the huge political controversy surrounding the plans.</p>

<p>Dr. Pascal Colombani, Special Envoy of French President Francois Hollande for the nuclear partnership with South Africa, expects the long-awaited invitation from Pretoria to nuclear countries to submit their bids, to come anytime between now and Spring.</p>

<p>He said in Johannesburg on Monday France had expected this “Request for Proposals (RFPs)” to be issued to France and the other bidding countries by the end of March or beginning of April.</p>

<p>The South African nuclear proposal, which envisages up to 9,600 megawatts of extra electricity being generated by between six and eight new reactors, has reportedly been caught up in the political feud between President Jacob Zuma and Finance Minister Pravin Gordhan who reputedly believes the country cannot afford it.</p>

<p><a href="http://www.iol.co.za/business/news/france-confident-sa-nuke-power-build-will-push-ahead-2029316" rel="nofollow">Read More ….</a></p>

<div class="embed-responsive embed-responsive-16by9">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/GfnftYH5MN4" frameborder="0" allowfullscreen=""></iframe>
</div>
<p><br /></p>
<div class="embed-responsive embed-responsive-16by9">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/nqin5Bt_x-Q" frameborder="0" allowfullscreen=""></iframe>
</div>
<p><br /></p>

<h2 id="nuclear-energy-explained">Nuclear Energy Explained</h2>
<div class="embed-responsive embed-responsive-16by9">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/d7LO8lL4Ai4" frameborder="0" allowfullscreen=""></iframe>
</div>

            </article>
    </div>
</div>
<?php
    include ENV_ROOT . 'includes/footer.php';
    include ENV_ROOT . 'includes/javascripts_basic.html';
?>


    </body>
</html>
