<?php
$strEnvConfigFile = '../environment/config.php';
$intLevel = 0;
while (!file_exists($strEnvConfigFile)) {
    $strEnvConfigFile = '../' . $strEnvConfigFile;
    $intLevel++;
    // Iterate up 4 levels before giving up - this should never happen!
    if ($intLevel > 3) {
        die('Fatal error - environment configuration file could not be located');
    }
}
include_once $strEnvConfigFile;

$strPageTitle = 'CV Writing Africa Job Hunting Tips';
$strPageDescription = 'CV writing tips for the African Industry. Job hunting? Get free info here.';
$strPageKeywords = 'CV writing Africa Job hunting tips';
$strPageAuthor = 'AdoGreen Africa Recruiment Agency';
$strPageImg = ENV_ROOTURL . '/assets/img/candidate-cv-writing.png';
$strPageCountry = '';
$strPageSector = '';
$strPageJobList = '';

include_once ENV_ROOT . 'includes/header.php';
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12  background-cv-writing animate-fade-in">
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="heading-underline h1 animate-fade-in"><b>CV Writing </b> - Job Hunting Tips</h1>
            <h3 class="text-center heading-upper animate-fade-in">If you are looking for career advice, informative industry information, how to write a better CV, becoming more marketable, tips on job hunting and also coaching through the resignation process read some of our easy tips on the recruitment process.</h3>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4 animate-fade-in">
            <img class="img-responsive" src="<?php echo $strPageImg; ?>" width="100%" alt "<?php echo $strPageTitle; ?>">
                 <div class="well margin-20">
                <h3>Free Downloadable CV Examples</h3>
                <i class="fa fa-file-word-o"><a href="<?php echo ENV_ROOTURL; ?>assets/docs/candidates/cv-admin-example.doc"> Admin CV Example</a></i><br />
                <i class="fa fa-file-word-o"><a href="<?php echo ENV_ROOTURL; ?>assets/docs/candidates/cv-artisan-example.doc"> Artisan CV Example</a></i><br />
                <i class="fa fa-file-word-o"><a href="<?php echo ENV_ROOTURL; ?>assets/docs/candidates/cv-geologist-example.doc">Geologist CV Example</a></i>
            </div>
            <div class="hidden-xs">
            </div>
        </div>
        <div class="col-md-6">
            <p><strong>CV WRITING TIP NO 1/31:</strong> Avoid sending scanned copies of your CV. Most database CV searches are done through key word searches. Your CV will not come up on a search if recognised as a fax/scanned copy as the system will recognise it as an image file and therefore it will not be searchable</p>
<!--            <p><strong>CV WRITING TIP NO 2:</strong> Use as many relevant key words (to your experience) on your CV. Remember that when your CV is saved onto a database, people will do a search to find relevant candidates by key-word searching. If you have done SAP and it is not on your CV, a search for all candidates having done SAP will mean that your CV won&rsquo;t come up on the search if omitted.</p>
            <p><strong>CV WRITING TIP NO 3.</strong> Make sure you elaborate in detail on actual duties and responsibilities in each job position. Recruiters and companies will want to see specifically what you have done within each position. Leaving this off may get people to presume you do not have enough experience for the relevant requirement</p>
            <p><strong>CV WRITING TIP NO 4:</strong> Do not story-tell on your CV. Ideally, you need a bullet pointed breakdown of duties and&nbsp;responsibilities. You CV must be punchy, to the point, and detailed in this. No one has time to read a long story of when and how you got the job, why you enjoyed it, the things you like doing etc. People scan over a CV for a quick overview. A story-telling CV will get side-lined most of the time.</p>
            <p><strong>CV WRITING TIP NO 5:</strong> Dates are EXTREMELY important. Surprisingly, many people just list their jobs, or for example say 8 years at a certain company, then 9 months at this company etc. This can&nbsp;raise questions in employment gaps, possibly sabbaticals, and unemployment periods and potentially create a bit of suspicion as to why you would have omitted this information. It does not have to be for e.g.: 4th March 2012 - 19 April 2014, but rather March 2012 - April 2014 will suffice. Dates place your experience within a progressive and linear time frame and assist with&nbsp;being short-listed more easily.</p>
            <p><strong>CV WRITING TIP NO 6:</strong> Do NOT write your whole CV in capitols. This is highly unprofessional, as well as making the CV very difficult to read owing to incorrect/no punctuation. It is difficult to raise emphasis on points you would like to with this very incorrect format and it does not make your CV well presented, not to many seriously unattractive. Some people will go as far as to presume laziness on the part of the candidate. </p>
            <p><strong>CV WRITING TIP NO 7:</strong> Put reasons for leaving under each position unless specifically needing to be discussed confidentially. This will fast track the shortlisting process for you in helping people to understand your motives, requirements and career intentions.</p>
            <p><strong>CV WRITING TIP NO 8:</strong> Don't over-format your CV. Avoid hundreds of boxes and columns, with unused space that lengthens&nbsp;and complicates your CV unnecessarily. Over-formatting makes a CV hard to understand as one sometimes needs to jump to many different sections to retrieve relevant information in context which can frustrate the person reading the CV. This is especially true when people reduce the font size to cram&nbsp;in an&nbsp;excessive amount of information into a small space.&nbsp;</p>
            <p><strong>CV WRITING TIP NO 9.</strong> Limit the length of your CV without omitting important information. A 15&nbsp;page CV might seem impressive, but length of CV is not an indication of competence. You will actually put people off if the content of your CV is not punchy and highly relevant in a condensed format. Cut out the 'life story guff' and focus on technical competence. Summarise&nbsp;your project just enough to secure interest from&nbsp;the client to want to discuss it further in an interview. A suggestion of 2 - 4 pages on average is reasonable with the exception&nbsp;given to more senior candidates.&nbsp;(This is for CVs within the African continent, generally)</p>
            <p><strong>CV WRITING TIP NO 10/30:</strong> Taylor your CV to the position you are applying for where possible. If you are not someone who plays a numbers game and submits your CV to every job under the sun, be selective in the keywords you use, and submit a much targeted application relevant to your experience. Some people may be the perfect fit for a job, but their CVs content disqualifies them in the shortlisting process without them being aware of it. Be detailed yet specific. (Less is not always more...)</p>
            <p><strong>CV WRITING TIP NO 11:</strong> Be more specific on your CV. A concise and to the point CV is vital BUT do not generalise to much that it disqualifies you from being shortlisted through appearing not to have enough experience. If people report to you, mention how many. If working on SAP, mention whether you are basic, intermediate or advanced&hellip; If a diesel mechanic, mention specifically the machines worked on. This will make you more targeted in your application, saving you and the client time.</p>
            <p><strong>CV WRITING TIP NO 12:</strong> Do NOT summarise and cluster all duties and responsibilities from all jobs into one main section. Rather let these be job specific in putting the relevant points under the relevant job according to date and time. In this way, people can see when, and for how long you had exposure in the particular task. It may seem impressive, but in not doing it the 'summary&nbsp;way', you will frustrate those going through your CV in not being able to understand and define your experience more specifically. </p>
            <p><strong>CV WRITING TIP NO 13:</strong> Do NOT copy and paste identical duties and responsibilities under 2 different positions. This will make your CV boring, questionable and predictable not to mention that it won't promote you in enabling the client think you are an exceptional candidate to be considered. Your CV will lose impact having a sense of monotony to it. Doing this may jeopardize your competitiveness and your experience may be questioned. After all, why would someone move for the EXACT same duties and responsibilities and can it even be plausible?</p>
            <p><strong>CV WRITING TIP NO 14:</strong> Do NOT have ANY spelling mistakes or grammatical errors on your CV, especially a wrong email address/old tel no. Your CV sells who you are, and so you do not want project the message of having a lack in attention to detail, excellence and professionalism. Check you tenses as cases. Do not mix present tense and past tense, first person and third person as well as sentence and title case. Get a fee friends to check your CV and give their input if you are not sure. </p>
            <p><strong>CV WRITING TIP NO 15:</strong> There&rsquo;s no need to get too personal on your CV. No one cares if you hate unfairness, still have respect for the elderly, still want to climb Mt Everest etc.&hellip; Be professional and stick to having a business focus, as technical as possible, with emphasis on your commercial experience and career goals. An employer can always ask about personal interests and hobbies in an interview. Should you be going through a divorce, it can be sensitive and best to avoid detail, and so do not rope people into your personal concerns before you have even been shortlisted. </p>
            <p><strong>CV WRITING TIP NO 16:</strong> Do NOT exaggerate or oversell yourself on your CV. People are mostly shortlisted on the merit of their skills and experience. If you fabricate, you will have an embarrassing interview when not able to give plausible answers to&nbsp;your experience. Should you study like crazy before the interview to give an interviewer text book answers they may need for certain skills required, and you end up getting the job, your technical inability will soon come to light and you may even lose your job if you represent yourself inaccurately.</p>
            <p><strong>CV WRITING TIP NO 17:</strong> Do not leave any gaps in your work record &ndash; employers often assume the worst. For example: that you were fired/unable to get work through a bad reference, had limited skill not being competitive enough which left you searching in the market etc. If you took a sabbatical, were studying, or not able to find a suitable position in line with your career focus, whatever the reason, do not leave a big gap. Be honest, but you do not have to go into lengthy detail. Further information can be requested from you/discussed in an interview.</p>
            <p><strong>CV WRITING TIP NO 18:</strong> Do not take up a whole A4 page with personal contact detail or simply with &lsquo;CURRICULUM VITAE Of JOE SOAP&rsquo; This is an utter waste of space and separates your name from the rest of your CV. It would be better to create a small header with your name at the top of the page that will then appear by default on each page with a page number that you can insert. </p>
            <p><strong>CV WRITING TIP NO 19:</strong> Use a confident tone and positive language. Do not come across as the victim on your CV. You do not need to have a long profile overview as to how disadvantaged you were etc., or in reasons for leaving that you were treated unfairly, etc. etc. Do you be aggressive on your CV criticising people/organisations, or promoting your personal beliefs. Keep it professional, positive and to the point. The emphasis is your skills and experience, not moral or ethical preferences. </p>
            <p><strong>CV WRITING TIP NO 20:</strong> It is important to highlight notable past WORK&nbsp;achievements. This is helpful in bringing attention to your abilities beyond basic job requirements. Team achievements are generally not impactful, but individual achievement is, so don&rsquo;t bother with group achievements unless you specifically lead that group. Achievements should generally be work related &ndash; not solos in the school choir or being 1<sup>st</sup>&nbsp;team rugby etc. Keep it business related, or educationally related regarding tertiary studies if you achieved with distinctions etc.) A CV is not your whole life story, but rather your employment record. Anything beyond this can be asked in an interview, and if not asked, it is not necessarily important to the interviewer at that time&hellip;</p>
            <p><strong>CV WRITING TIP NO 21:</strong> Battling to give yourself a &lsquo;meaty&rsquo; representation? Google&rsquo;s your friend! If you have somewhat skeletal/ weak job descriptions as to what you do and can&rsquo;t seem to generate a beefy CV for yourself, google job descriptions of similar positions to yours to get ideas on how to elaborate and express what you do in more detail, but staying true to your current job function. You will be surprised as to how many obvious things are mentioned in a professional and impressive way specific to your current function. Be sure not to include anything that you do not have exposure to/ experience in. Remember that you cannot fabricate information though as you may be asked about it in an interview!</p>
            <p><strong>CV WRITING TIP NO 22:</strong> Make sure you include all the relevant personal info needed. Nationality is vitally important to include on your CV as well as current location. Far more often than not, this has a direct impact on the outcome of your application/s, so do not waste your time and a client&rsquo;s by omitting it as it might delay people from shortlisting you, when another suitable candidate includes the relevant information required.</p>
            <p><strong>CV WRITING TIP NO 23:</strong> Put your educational details above your experience at the top of your CV. Some jobs have a minimum educational requirement, and should you not qualify, it seriously helps the client/consultant see where to take it a lot quicker. If you have the right educational background required for the position, this will speed up the screening process for you. You may have however studied something else, not relevant to the job you are applying for, where emphasis can rather be placed on your interests through what you have studied. With this, you may be considered for something else that you may not be aware of being advertised.</p>
            <p><strong>CV WRITING TIP NO 24:</strong> Get recommendations and sell yourself. If on LinkedIn, hook up with old contacts you reported to, to give you a recommendation, and simply post the link on your CV as a form of a reference for employers to go to. However, make sure that these recommendations are from people you reported to, NOT WORK COLLEAGUES or RANDOM FRIENDS! You want to add weight to this resource so don&rsquo;t waste people&rsquo;s time with random recommendations. They must be relevant.</p>
            <p><strong>CV WRITING TIP NO 25:</strong> Simplicity is key: Avoid numerous tables and tabs, columns and boxes that make your information compact and difficult to read. It may seem like a good idea, but keep things chronological in a basic format, bulleting pointing key performance areas. Make sure the space on your CV is used wisely. Remember that not all companies have Word 2010 and NO POWERPOINT CVS ever! Avoid writing your CV in Excel. It makes for difficult reading.</p>
            <p><strong>CV WRITING TIP NO 26:</strong> When putting a photo on your CV - Many people are reluctant to put it on for personal and other reasons. It certainly is not a prerequisite, but it can make one's CV more personable and potentially work in your favour . As long as it is a plain, professional ID type head and shoulder photo with one being neat and well groomed. Some people really have no idea and anything outside of this is rather not advised. For ladies, no seductive poses with inappropriate dress code etc. and guys keeping it simple as well, being very neat, especially when it comes to hair. Don't pose next to some Lamborghini / something inappropriate like that. First impressions last, so just remember that a photo can actually be very advantageous if the client is looking for someone 'like you' but it can be incriminating if you do not meet the 'organisational fit'. Keeping it plain, professional and tasteful will put you on good foot. </p>
            <p>I would give the same advice to any business related profile picture. FYI - be careful if you have some unique name and are on Facebook. Employers may find you without being connected. Dodgy pics can cost one a career opportunity and have. PLEASE NOTE: If you are selective who/what you are applying for a photo is good, otherwise if you mass email your CV anywhere, rather leave it off.</p>
            <p><strong>CV WRITING TUP NO 27:</strong> Make sure your CV is saved correctly and you apply to jobs correctly. When applying to a particular position, make sure your CV is saved as for e.g.: &lsquo;CV of Jack Smith&rsquo; not &lsquo;CV.doc&rsquo; Also do not apply to a position saying, &lsquo;Application for position&rsquo; / &lsquo;Find CV for position advertised&rsquo; Agencies and companies advertise many positions and they are not telepathic in automatically knowing what you have applied to. BE SPECIFIC. In the subject line say for e.g.: JACK SMITH &ndash; Application for Mechanical Engineer&rsquo; If you want your CV viewed quicker giving the recipient less admin, cooperate to put yourself in the best position for a CV response.</p>
            <p><strong>CV WRITING TIP NO 28:</strong> Make sure your CV is always immediately available and properly updated. Are you still running around with memory sticks, and a wad of certificates that you are always scanning for applications? Create a template in your drafts within your private email account (Yahoo/Gmail etc.) and edit in accordance with the position you are applying to. Email yourself a complete and detailed application from yourself (from drafts), and should you want to apply to a position, simply click forward on that email now sent to your own inbox, and edit the email accordingly. Bcc yourself in on all your applications so you can track what you are doing. No more carrying around of memory sticks and certificates that can get lost and no more forgetting who and what you applied to.</p>
            <p><strong>CV WRITING TIP NO 29:</strong> Make sure the info on your CV makes sense and the dates add up. Your CV on every social media site must be consistent. I.e. Your Linkedin profile, Facebook info, Skillspages etc. must be consistent. Should two CVs of yours be viewed through different sources (and people do) with contradicting dates, you could disqualify yourself from being shortlisted as it may be too suspicious. Be honest on your CV and don&rsquo;t make up stuff, especially dates. Should an employer want a reference on you and speak with someone who you worked with previously at a company where you have given falsified information, kiss the job goodbye. Don&rsquo;t take chances with such a important document. These days it is so easy to get accurate information on somebody owing to the advancement of social media. (Remember that you can be found on a simple google search)</p>
            <p><strong>CV WRITING TIP NO 30:</strong> Do not oversell yourself. When candidates overemphasis generic character strengths and competencies that cannot be proven in relation to technical competence, you come across as a salesman and not a candidate. Stick to technical strengths and achievements, not overemphasising things like &lsquo;Great Leader&rsquo;</p>
    <p><strong>CV WRITING TIP NO 31:</strong> Be careful of the font you use. You may love certain weird fonts that ironically you never find anyone using. Well there is a reason for this. Don&rsquo;t get fancy on your CV. Keep is simple, clinical, and professional. The best fonts to choose from would be examples such as Arial, Calibri and Verdana. Keep it safe and avoid giving your reader a head ache. </p>-->
            <p>Click Here To Connect With Yvette's Posts On LinkedIn</p>
            <a href="https://www.linkedin.com/in/yvielee/detail/recent-activity/shares/"><img class="img-responsive" src="<?php echo ENV_ROOTURL; ?>assets/img/social-linkedin-yvette.png" width="100%" alt="Yvette Rautenbach Linkedin Recruitment Consultant Africa"></a>
        </div>
        <div class="col-md-2 animate-fade-in">



            <?php include ENV_ROOT . 'includes/Page_Sidebar.php'; ?>
        </div>
    </div>
</div>
<?php
include ENV_ROOT . 'includes/footer.php';
include ENV_ROOT . 'includes/js_scripts.php';
?>

</body>
</html>
